version: "2"
services:
  bot:
    build: .
    image: ekofiskctf/fiskebot
    restart: always
    environment:
      - "DISCORD_TOKEN=${DISCORD_TOKEN}"
      - "MONGODB_URI=${MONGODB_URI:-mongodb://mongo:27017}"
      - "LOGGING_LEVEL=${LOGGING_LEVEL:-INFO}"
      - "LOGGING_FORMAT=${LOGGING_FORMAT:-%(asctime)s:%(levelname)s:%(name)s: %(message)s}"
      - "LOGGING_FILE=${LOGGING_FILE}"
      - "LOGGING_DISCORD_LEVEL=${LOGGING_DISCORD_LEVEL:-ERROR}"
      - "COMMAND_PREFIX=${COMMAND_PREFIX:-!}"
      - "MAINTAINERS=${MAINTAINERS}"
      - "GUILD_IDS=${GUILD_IDS}"
      - "CATEGORY_WORKING=${CATEGORY_WORKING:-working}"
      - "CATEGORY_DONE=${CATEGORY_DONE:-done}"
      - "CATEGORY_ARCHIVE_PREFIX=${CATEGORY_ARCHIVE_PREFIX:-archive}"
      - "CHANNEL_EXPORT=${CHANNEL_EXPORT:-export}"
      - "CHANNEL_LOGGING_ID=${CHANNEL_LOGGING_ID}"
      - "CHANNEL_NAME_DELIMITER=${CHANNEL_NAME_DELIMITER}"
      - "CTFTIME_TEAM_ID=${CTFTIME_TEAM_ID}"
      - "CTFTIME_TEAM_NAME=${CTFTIME_TEAM_NAME}"
    volumes:
      - ./bot:/home/bot
      - ./backups:/home/bot/backups
    depends_on:
      - mongo
    stop_signal: SIGKILL
  mongo:
    image: mongo:4.4.5
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mdb:/data/db
      - mdb_config:/data/configdb

volumes:
  mdb:
    external: true
  mdb_config:
    external: true
