version: "2"
services:
  bot:
    build: .
    image: kfbi/igctf:latest
    restart: always
    volumes:
      - ./bot:/bot
      - ./backups:/home/bot/backups
    depends_on:
      - mongo
    env_file:
      - bot-variables.env
    stop_signal: SIGKILL
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mdb:/data/db
      - mdb_config:/data/configdb

volumes:
  mdb:
    external: true
  mdb_config:
    external: true