name: DigitalOcean CICD

on:
    push:
        branches:
            - main
    workflow_dispatch:

permissions: {}

env:
    USER: cee
    APP_PATH: /home/cee/app/fiskebot/
    RUNNER_HOME: /home/github
    HOST: ${{ secrets.DEPLOY_IP }}
    DOCKER_COMPOSE: docker-compose.yml
    SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}

jobs:
    build:
        runs-on: digitalocean
        steps:
            - uses: actions/checkout@v3
            - name: Configure SSH on github runner
              run: |
                mkdir -p "$RUNNER_HOME/.ssh/"
                echo "$SSH_KEY" > "$RUNNER_HOME/.ssh/private.pem"
                chmod 600 "$RUNNER_HOME/.ssh/private.pem"
                printf "Host docean\n  HostName $HOST\n  User $USER\n  IdentityFile $RUNNER_HOME/.ssh/private.pem\n  StrictHostKeyChecking no\n" > "$RUNNER_HOME/.ssh/config"
            - name: Build docker image
              run: |
                docker build -t fiskebot .
            - name: Deploy docker compose and .env file
              run: |
                scp "$DOCKER_COMPOSE" "docean:$APP_PATH/$DOCKER_COMPOSE"
                ssh docean "cd $APP_PATH && echo 'just a test, workflow was here' >> workflow.txt"
            - name: Cleanup SSH configs
              if: always()
              run: |
                rm -rf "$RUNNER_HOME/.ssh"
